import { IoMdPeople as icon } from 'react-icons/io';

export default {
  title: 'Client',
  name: 'client',
  type: 'document',
  icon,
  fields: [
    {
      title: 'Active',
      name: 'isActive',
      type: 'boolean',
      description: `Is this person an active client?`,
      validation: (Rule) => Rule.required(),
    },
    {
      title: " ",
      name: 'clientFullName',
      type: 'object',
      options: {
        columns: 2, // Defines a grid for the fields and how many columns it should have
      },
      fields: [
        {
          title: 'First Name',
          name: 'firstName',
          type: 'string',
          validation: (Rule) => Rule.required().min(2).warning('First names should be longer than 2 characters'),
        },
        // {
        //   title: 'Email',
        //   name: 'email',
        //   type: 'string'
        // },
        // {
        //   title: 'Temp Password',
        //   name: 'password',
        //   type: 'string'
        // },
        {
          title: 'Second Name',
          name: 'secondName',
          type: 'string',
          validation: (Rule) => Rule.required().min(2).warning('Second names should be longer than 2 characters'),
        },
      ]
    },
    {
      title: 'Age',
      name: 'age',
      type: 'number',
    },
    {
      title: 'UID',
      name: 'uid',
      type: 'string',
      description: `This is generated by the signup process on Google Firebase. For now, we need to create a new user there then paste the generated UUID here.`
    },
    {
      name: 'link',
      title: 'Link',
      type: 'string',
    },
    {
      title: 'Avitar',
      name: 'avitar',
      type: 'image',
      description: `Put an image of the person here. This will appear on their profile screen on the app.`,
      options: {
        hotspot: true, // Make the image editable
      },
    },
    {
      title: 'Notes',
      name: 'notes',
      type: 'array',
      of: [{ type: 'block' }],
    },
    {
      title: 'Assigned Workout Plans',
      name: 'workoutPlanReferences',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'assignedWorkoutPlans',
              title: 'Workout Plans',
              type: 'reference',
              to: [{ type: 'plan' }],
            }
          ],
          preview: {
            select: {
              title: 'assignedWorkoutPlans.name',
              subtitle: 'assignedWorkoutPlans.description',
              media: 'assignedWorkoutPlans.mainImage.asset'
            }
          }
        }
      ]
    },
    {
      title: 'Assigned Courses',
      name: 'courseReferences',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'assignedCourses',
              title: 'Courses',
              type: 'reference',
              to: [{ type: 'course' }],
            }
          ],
          preview: {
            select: {
              title: 'assignedCourses.name',
              subtitle: 'assignedCourses.description',
              media: 'assignedCourses.mainImage.asset'
            }
          }
        }
      ]
    },
  ],
  preview: {
    select: {
      title: 'clientFullName.firstName',
      subtitle: 'clientFullName.secondName',
      media: 'avitar',
    },
  },
  initialValue: {
    isActive: true,
  },
};
